backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: blog-post}
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Description, name: description, widget: text}
      - {label: Featured Post, name: featuredpost, widget: boolean, default: false}
      - {label: Featured Image, name: featuredimage, widget: image}
      - {label: Body, name: body, widget: markdown}
      - {label: Tags, name: tags, widget: list}

  - name: services
    label: Services
    folder: src/pages/services
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: service}
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: text}
      - {label: Featured Post, name: featuredpost, widget: boolean, default: false}
      - {label: Featured Image, name: featuredimage, widget: image}
      - {label: Body, name: body, widget: markdown}

  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Landing Page
        name: index
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: index-page}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Blurbs, name: blurbs, widget: list, fields:  [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Title, name: title, widget: text}, {label: Text, name: text, widget: text}, {label: Link, name: link, widget: text}]}]}
          - {label: Body, name: body, widget: markdown}
      - file: src/pages/about/index.md
        label: About Page
        name: about
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: about-page}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string, required: false }
          - {label: Description, name: description, widget: string, required: false }
          - {label: Intro, name: intro, widget: object, fields: [{label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Title, name: title, widget: text, required: false }, {label: Text, name: text, widget: text, required: false }]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full image, name: full_image, widget: image}
      - file: src/pages/documents/index.md
        label: Document Page
        name: document
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: document-page}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string, required: false}
          - {label: Description, name: description, widget: string, required: false}
          - {label: Documents, name: documents, widget: object, fields: [{ label: Document, name: document, widget: list, required: false, fields: [{ label: Image, name: image, widget: image }, { label: Title, name: title, widget: text, required: false }, { label: Description, name: description, widget: text, required: false }, { label: Upload File, name: file, widget: file, public_folder: '/static/img' }]}]}
      - file: src/pages/contact/index.md
        label: Contact Page
        name: contact
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: contact-page}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string, required: false}
          - {label: Description, name: description, widget: string, required: false}
          - {label: Body, name: body, widget: markdown}
          - {label: Employees, name: employees, widget: object, fields: [{ label: Heading, name: heading, widget: string, required: false }, { label: Description, name: description, widget: text, required: false }, { label: Employee, name: employee, widget: list, fields: [{ label: Image, name: image, widget: image }, { label: Name, name: name, widget: text }, { label: Phone, name: phone, widget: text }, { label: Email, name: email, widget: text }]}]}